### ISSUE TITLE
Developer can configure test_changes for multiple commands

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/test_changes#8]
Something like this:

``` yaml

---
rspec:
  finding_patterns:
    ^lib/(.+)\.rb: spec/\1_spec.rb
    ^spec/(.+)_spec.rb: spec/\1_spec.rb
  verbose: true
rubocop:
  finding_patterns:
    ^(.+)\.rb: \1.rb
  verbose: true
```
